# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 2007 - 2019 Intel Corporation.

#
# Makefile for the Intel(R) Gigabit Ethernet Linux Driver
#

obj-$(CONFIG_IGB) += igb.o

igb-objs := igb_main.o \
	e1000_api.o \
	igb_ethtool.o \
	igb_hwmon.o \
	e1000_mbx.o \
	e1000_mac.o \
	e1000_manage.o \
	e1000_nvm.o \
	igb_param.o \
	e1000_phy.o \
	igb_procfs.o \
	igb_vmdq.o \
	e1000_82575.o \
	e1000_i210.o \
	kcompat.o
